# Generated by Django 5.2.8 on 2025-11-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('sotiladi', 'Sotiladi'), ('ijaraga', 'Ijaraga')], default='sotiladi', max_length=50)),
                ('title', models.CharField(default='empty', max_length=60)),
                ('kategoriya', models.CharField(choices=[('texnika', 'Texnika'), ('transport', 'Transport')], default='teexnika', max_length=60)),
                ('tavsilot', models.TextField(default='mahsulot:')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rasm', models.FileField(null=True, upload_to='products/')),
                ('number', models.CharField(default='+998000000000', max_length=13)),
                ('telegram', models.CharField(default='@username', max_length=60)),
            ],
        ),
    ]
