# Generated by Django 5.2.8 on 2025-11-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='kategoriya',
            field=models.CharField(choices=[('texnika', 'Texnika'), ('transport', 'Transport'), ('uskunalar', 'Uskunalar'), ('kochmas-mulk', 'Kochmas-mulk')], default='teexnika', max_length=60),
        ),
    ]
